import Navbar from "@/components/NavBar";
import Image from "next/image";
import Menu from "@/components/Menu";
import Link from "next/link";
import { Locale, routing } from "@/i18n/routing";
import type { Metadata } from "next";
import { NextIntlClientProvider } from "next-intl";
import { getTranslations } from "next-intl/server";
import { getMessages } from "next-intl/server";
 import { notFound } from "next/navigation";
import "../globals.css";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode;
  params: { locale: Locale };
}>) {
  const { locale } = await params;
  if (!routing.locales.includes(locale as Locale)) {
    notFound();
  }
  // Providing all messages to the client
  // side is the easiest way to get started
  const messages = await getMessages();
  // Add direction based on locale
  const dir = locale === 'ku' || locale === 'ar' ? 'rtl' : 'ltr';
  const t = await getTranslations("layout");

  return (
    <div lang={locale} dir={dir} className= "font-NotoKufiArabic ">
        <NextIntlClientProvider messages={messages}>
        <div className="h-screen flex">
      {/* LEFT */}
      <div className="w-[10%] md:w-[5%] lg:w-[16%] xl:w-[14%] p-4">
        <Link
          href="/"
          className="flex items-center justify-center lg:justify-start gap-2"
        >
          <Image src="/logo1.png" alt="logo" width={55} height={55} className="hidden lg:block" />
          <span className="hidden lg:block font-medium">{t("name")}</span>
        </Link>
        <Menu />
      </div>
      {/* RIGHT */}
          <div 
            className="w-[80%] md:w-[92%] lg:w-[84%] xl:w-[86%] bg-[#F7F8FA] h-full overflow-scroll flex flex-col">
                <Navbar />
        {children}
      </div>
    </div>
        </NextIntlClientProvider>
    </div>
  );
}
